<script lang="ts">
	import ArrowLeft from '@lucide/svelte/icons/arrow-left';
	import Printer from '@lucide/svelte/icons/printer';
	import Badge from '$lib/components/ui/badge/badge.svelte';
	import Button from '$lib/components/ui/button/button.svelte';
	import { formatDate, proposalStatusClass, statusLabel } from '$lib/app/format';
	import { formatMoney } from '$lib/app/currency';
	import type { PageData } from './$types';

	let { data } = $props<{ data: PageData }>();
</script>

<svelte:head>
	<title>Preview {data.proposal.proposal_number} - Freelance OS</title>
	<meta name="description" content={`Preview proposal ${data.proposal.proposal_number}.`} />
</svelte:head>

<div class="mx-auto max-w-4xl space-y-5">
	<div class="flex items-center justify-between print:hidden"><a href={`/proposals/${data.proposal.id}`} class="inline-flex items-center gap-1.5 text-xs text-muted-foreground hover:text-foreground"><ArrowLeft class="size-3.5" /> Back to proposal</a><Button type="button" variant="outline" size="sm" onclick={() => window.print()}><Printer class="size-3.5" /> Print proposal</Button></div>

	<article class="overflow-hidden rounded-lg border border-border bg-card shadow-sm print:rounded-none print:border-0 print:shadow-none">
		<header class="border-b border-border p-6 sm:p-10"><div class="flex flex-col gap-8 sm:flex-row sm:items-start sm:justify-between"><div class="min-w-0"><p class="text-xs font-semibold tracking-[0.14em] text-muted-foreground uppercase">{data.issuer.name ?? 'Proposal issuer'}</p><h1 class="mt-3 text-3xl font-semibold tracking-tight">{data.proposal.title}</h1>{#if data.issuer.legalName && data.issuer.legalName !== data.issuer.name}<p class="mt-2 text-sm text-muted-foreground">{data.issuer.legalName}</p>{/if}{#if data.issuer.address}<p class="mt-4 whitespace-pre-line text-sm leading-6 text-muted-foreground">{data.issuer.address}</p>{/if}</div><div class="min-w-0 sm:text-right"><p class="text-xs font-medium text-muted-foreground">Proposal number</p><p class="mt-1 text-lg font-semibold">{data.proposal.proposal_number}</p><Badge variant="outline" class={`mt-3 ${proposalStatusClass(data.proposal.status)}`}>{statusLabel(data.proposal.status)}</Badge><div class="mt-5 grid grid-cols-2 gap-x-6 gap-y-3 text-left text-sm sm:text-right"><div><p class="text-xs text-muted-foreground">Issue date</p><p class="mt-1 font-medium">{formatDate(data.proposal.issue_date, { month: 'short', day: 'numeric', year: 'numeric' })}</p></div>{#if data.proposal.valid_until}<div><p class="text-xs text-muted-foreground">Valid until</p><p class="mt-1 font-medium">{formatDate(data.proposal.valid_until, { month: 'short', day: 'numeric', year: 'numeric' })}</p></div>{/if}</div></div></div></header>
		{#if data.proposal.overview}<section class="border-b border-border p-6 sm:p-10"><p class="text-xs font-semibold tracking-[0.14em] text-muted-foreground uppercase">Overview</p><p class="mt-3 max-w-3xl whitespace-pre-line text-sm leading-6">{data.proposal.overview}</p></section>{/if}

		<section class="grid gap-8 border-b border-border p-6 sm:grid-cols-2 sm:p-10"><div><p class="text-xs font-semibold tracking-[0.14em] text-muted-foreground uppercase">From</p><p class="mt-3 text-sm font-semibold">{data.issuer.name ?? 'Proposal issuer'}</p>{#if data.issuer.email}<p class="mt-2 text-sm text-muted-foreground">{data.issuer.email}</p>{/if}{#if data.issuer.phone}<p class="mt-1 text-sm text-muted-foreground">{data.issuer.phone}</p>{/if}{#if data.issuer.website}<p class="mt-1 text-sm text-muted-foreground">{data.issuer.website}</p>{/if}{#if data.issuer.taxId}<p class="mt-3 text-sm text-muted-foreground">{data.issuer.taxIdLabel ?? 'Tax ID'}: {data.issuer.taxId}</p>{/if}</div><div class="sm:text-right"><p class="text-xs font-semibold tracking-[0.14em] text-muted-foreground uppercase">Prepared for</p><p class="mt-3 text-sm font-semibold">{data.client?.name ?? 'Client'}</p>{#if data.client?.company}<p class="mt-1 text-sm text-muted-foreground">{data.client.company}</p>{/if}{#if data.client?.billing_address}<p class="mt-3 whitespace-pre-line text-sm leading-6 text-muted-foreground">{data.client.billing_address}</p>{/if}{#if data.client?.email}<p class="mt-3 text-sm text-muted-foreground">{data.client.email}</p>{/if}{#if data.client?.tax_id}<p class="mt-1 text-sm text-muted-foreground">{data.client.tax_id_label ?? 'Tax ID'}: {data.client.tax_id}</p>{/if}</div></section>

		<section class="space-y-8 p-6 sm:p-10">{#if data.proposal.scope}<div><p class="text-xs font-semibold tracking-[0.14em] text-muted-foreground uppercase">Scope and deliverables</p><p class="mt-3 whitespace-pre-line text-sm leading-6">{data.proposal.scope}</p></div>{/if}{#if data.proposal.timeline || data.proposal.payment_terms}<div class="grid gap-8 sm:grid-cols-2">{#if data.proposal.timeline}<div><p class="text-xs font-semibold tracking-[0.14em] text-muted-foreground uppercase">Timeline</p><p class="mt-3 whitespace-pre-line text-sm leading-6">{data.proposal.timeline}</p></div>{/if}{#if data.proposal.payment_terms}<div><p class="text-xs font-semibold tracking-[0.14em] text-muted-foreground uppercase">Payment terms</p><p class="mt-3 whitespace-pre-line text-sm leading-6">{data.proposal.payment_terms}</p></div>{/if}</div>{/if}
			<div><div class="grid grid-cols-[minmax(0,1fr)_70px_110px] gap-3 border-b border-border pb-3 text-xs font-semibold tracking-wide text-muted-foreground uppercase"><span>Description</span><span class="text-right">Qty</span><span class="text-right">Amount</span></div><div class="divide-y divide-border">{#each data.lineItems as item (item.id)}<div class="grid grid-cols-[minmax(0,1fr)_70px_110px] gap-3 py-4 text-sm"><div class="min-w-0"><p class="font-medium">{item.description}</p><p class="mt-1 text-xs text-muted-foreground">{formatMoney(item.unit_price, data.proposal.currency_code)} each{item.tax_rate ? ` · ${item.tax_rate}% tax` : ''}</p></div><span class="text-right text-muted-foreground">{item.quantity}</span><span class="text-right font-medium">{formatMoney(item.amount, data.proposal.currency_code)}</span></div>{/each}</div><div class="mt-6 ml-auto w-full max-w-xs space-y-2 text-sm"><div class="flex justify-between"><span class="text-muted-foreground">Subtotal</span><span>{formatMoney(data.proposal.subtotal, data.proposal.currency_code)}</span></div><div class="flex justify-between"><span class="text-muted-foreground">Tax</span><span>{formatMoney(data.proposal.tax_total, data.proposal.currency_code)}</span></div><div class="flex justify-between border-t border-border pt-3 text-base font-semibold"><span>Total</span><span>{formatMoney(data.proposal.total, data.proposal.currency_code)}</span></div></div></div>
		</section>

		{#if data.proposal.notes || data.proposal.terms || data.issuer.footerNote}<footer class="border-t border-border bg-muted/30 p-6 sm:p-10"><div class="grid gap-8 sm:grid-cols-2">{#if data.proposal.notes}<div><p class="text-xs font-semibold tracking-[0.14em] text-muted-foreground uppercase">Notes</p><p class="mt-3 whitespace-pre-line text-sm leading-6">{data.proposal.notes}</p></div>{/if}{#if data.proposal.terms}<div><p class="text-xs font-semibold tracking-[0.14em] text-muted-foreground uppercase">Terms</p><p class="mt-3 whitespace-pre-line text-sm leading-6">{data.proposal.terms}</p></div>{/if}</div>{#if data.issuer.footerNote}<p class="mt-8 border-t border-border pt-5 text-center text-xs text-muted-foreground">{data.issuer.footerNote}</p>{/if}</footer>{/if}
	</article>
</div>
