<script lang="ts">
	import ArrowLeft from '@lucide/svelte/icons/arrow-left';
	import CheckCircle2 from '@lucide/svelte/icons/check-circle-2';
	import CreditCard from '@lucide/svelte/icons/credit-card';
	import Printer from '@lucide/svelte/icons/printer';
	import Send from '@lucide/svelte/icons/send';
	import Badge from '$lib/components/ui/badge/badge.svelte';
	import Button from '$lib/components/ui/button/button.svelte';
	import * as Card from '$lib/components/ui/card';
	import ConfirmActionDialog from '$lib/components/confirm-action-dialog.svelte';
	import Input from '$lib/components/ui/input/input.svelte';
	import Label from '$lib/components/ui/label/label.svelte';
	import { formatDate, invoiceStatusClass, statusLabel } from '$lib/app/format';
	import { formatMoney } from '$lib/app/currency';
	import type { ActionData, PageData } from './$types';

	let { data, form }: { data: PageData; form?: ActionData } = $props();
	let outstanding = $derived(Number(data.invoice.total) - Number(data.invoice.amount_paid));
</script>

<svelte:head><title>{data.invoice.invoice_number} - Freelance OS</title></svelte:head>

<div class="space-y-5">
	<div class="flex items-center gap-2 text-xs text-muted-foreground"><a href="/invoices" class="inline-flex items-center gap-1.5 hover:text-foreground"><ArrowLeft class="size-3.5" /> Invoices</a><span aria-hidden="true">/</span><span class="font-medium text-foreground">{data.invoice.invoice_number}</span></div>
	<header class="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
		<div><div class="flex flex-wrap items-center gap-2"><h1 class="text-2xl font-semibold tracking-tight">{data.invoice.invoice_number}</h1><Badge variant="outline" class={invoiceStatusClass(data.invoice.displayStatus)}>{statusLabel(data.invoice.displayStatus)}</Badge></div><p class="mt-1 text-sm text-muted-foreground">{data.client?.name ?? 'Unknown client'}{data.project ? ` · ${data.project.name}` : ''}</p></div>
		<div class="flex flex-wrap gap-2">
			<Button type="button" variant="outline" size="sm" onclick={() => window.print()}><Printer class="size-3.5" /> Print</Button>
			{#if data.invoice.status === 'draft'}<form method="POST" action="?/markSent"><Button type="submit" variant="outline" size="sm"><Send class="size-3.5" /> Mark sent</Button></form>{/if}
			{#if data.invoice.status !== 'void' && Number(data.invoice.amount_paid) === 0}<ConfirmActionDialog action="?/voidInvoice" title="Void invoice?" description="This will stop the invoice from being paid or sent." itemName={data.invoice.invoice_number} detail="The invoice will remain in your billing history as void and cannot be restored." triggerLabel="Void" confirmLabel="Void invoice" />{/if}
		</div>
	</header>

	{#if form?.message}<p role="status" class={form.success ? 'rounded-md border border-emerald-500/20 bg-emerald-500/10 px-3 py-2 text-sm text-emerald-700 dark:text-emerald-300' : 'rounded-md border border-destructive/20 bg-destructive/10 px-3 py-2 text-sm text-destructive'}>{form.message}</p>{/if}

	<section class="grid gap-px overflow-hidden rounded-md border border-border bg-border sm:grid-cols-3"><div class="bg-card p-4"><p class="text-xs font-medium text-muted-foreground">Invoice total</p><p class="mt-2 text-2xl font-semibold">{formatMoney(data.invoice.total, data.invoice.currency_code)}</p><p class="mt-1 text-xs text-muted-foreground">Issued {formatDate(data.invoice.issue_date, { month: 'short', day: 'numeric', year: 'numeric' })}</p></div><div class="bg-card p-4"><p class="text-xs font-medium text-muted-foreground">Paid</p><p class="mt-2 text-2xl font-semibold text-emerald-600 dark:text-emerald-400">{formatMoney(data.invoice.amount_paid, data.invoice.currency_code)}</p><p class="mt-1 text-xs text-muted-foreground">{data.payments.length} payment{data.payments.length === 1 ? '' : 's'} recorded</p></div><div class="bg-card p-4"><p class="text-xs font-medium text-muted-foreground">Balance due</p><p class={`mt-2 text-2xl font-semibold ${data.invoice.displayStatus === 'overdue' ? 'text-destructive' : ''}`}>{formatMoney(outstanding, data.invoice.currency_code)}</p><p class="mt-1 text-xs text-muted-foreground">Due {formatDate(data.invoice.due_date, { month: 'short', day: 'numeric', year: 'numeric' })}</p></div></section>

	<article class="rounded-md border border-border bg-card p-4 sm:p-6">
		<div class="flex flex-col gap-5 border-b border-border pb-5 sm:flex-row sm:justify-between">
			<div class="min-w-0"><p class="text-xs font-semibold tracking-[0.14em] text-muted-foreground uppercase">From</p><h2 class="mt-2 text-base font-semibold">{data.issuer.name ?? 'Invoice issuer'}</h2>{#if data.issuer.legalName && data.issuer.legalName !== data.issuer.name}<p class="mt-1 text-sm text-muted-foreground">{data.issuer.legalName}</p>{/if}{#if data.issuer.address}<p class="mt-3 whitespace-pre-line text-sm leading-6 text-muted-foreground">{data.issuer.address}</p>{/if}<div class="mt-3 space-y-1 text-xs text-muted-foreground">{#if data.issuer.email}<p>{data.issuer.email}</p>{/if}{#if data.issuer.phone}<p>{data.issuer.phone}</p>{/if}{#if data.issuer.website}<p>{data.issuer.website}</p>{/if}{#if data.issuer.taxId}<p>{data.issuer.taxIdLabel ?? 'Tax ID'}: {data.issuer.taxId}</p>{/if}</div></div>
			<div class="min-w-0 sm:max-w-xs sm:text-right"><p class="text-xs font-semibold tracking-[0.14em] text-muted-foreground uppercase">Bill to</p><h2 class="mt-2 text-base font-semibold">{data.billTo.name ?? 'Client'}</h2>{#if data.billTo.company}<p class="mt-1 text-sm text-muted-foreground">{data.billTo.company}</p>{/if}{#if data.billTo.address}<p class="mt-3 whitespace-pre-line text-sm leading-6 text-muted-foreground">{data.billTo.address}</p>{/if}<div class="mt-3 space-y-1 text-xs text-muted-foreground">{#if data.billTo.email}<p>{data.billTo.email}</p>{/if}{#if data.billTo.taxId}<p>{data.billTo.taxIdLabel ?? 'Tax ID'}: {data.billTo.taxId}</p>{/if}</div></div>
		</div>
		<div class="grid gap-4 pt-5 text-sm sm:grid-cols-3"><div><p class="text-xs text-muted-foreground">Invoice number</p><p class="mt-1 font-medium">{data.invoice.invoice_number}</p></div><div><p class="text-xs text-muted-foreground">Issue date</p><p class="mt-1 font-medium">{formatDate(data.invoice.issue_date, { month: 'short', day: 'numeric', year: 'numeric' })}</p></div><div><p class="text-xs text-muted-foreground">Due date</p><p class="mt-1 font-medium">{formatDate(data.invoice.due_date, { month: 'short', day: 'numeric', year: 'numeric' })}</p></div></div>
		{#if data.issuer.footerNote}<p class="mt-5 border-t border-border pt-4 text-center text-xs text-muted-foreground">{data.issuer.footerNote}</p>{/if}
	</article>

	<div class="grid gap-4 xl:grid-cols-[minmax(0,1fr)_330px]">
		<div class="space-y-4">
			<Card.Root class="gap-0 bg-card py-0"><Card.Header class="border-b border-border px-4 py-3"><Card.Title class="text-base">Line items</Card.Title><Card.Description class="mt-0.5 text-xs">The work covered by this invoice.</Card.Description></Card.Header><Card.Content class="p-0"><div class="divide-y divide-border">{#each data.lineItems as item (item.id)}<div class="grid grid-cols-[minmax(0,1fr)_70px_100px] gap-3 px-4 py-3 sm:px-5"><div class="min-w-0"><p class="truncate text-sm font-medium">{item.description}</p><p class="mt-1 text-xs text-muted-foreground">{item.quantity} × {formatMoney(item.unit_price, data.invoice.currency_code)}{item.tax_rate ? ` · ${item.tax_rate}% tax` : ''}</p></div><span class="text-right text-xs text-muted-foreground">{formatMoney(Number(item.quantity) * Number(item.unit_price), data.invoice.currency_code)}</span><span class="text-right text-sm font-medium">{formatMoney(item.amount, data.invoice.currency_code)}</span></div>{/each}</div><div class="space-y-2 border-t border-border px-4 py-4 text-sm sm:px-5"><div class="flex justify-between"><span class="text-muted-foreground">Subtotal</span><span>{formatMoney(data.invoice.subtotal, data.invoice.currency_code)}</span></div><div class="flex justify-between"><span class="text-muted-foreground">Tax</span><span>{formatMoney(data.invoice.tax_total, data.invoice.currency_code)}</span></div><div class="flex justify-between border-t border-border pt-3 text-base font-semibold"><span>Total</span><span>{formatMoney(data.invoice.total, data.invoice.currency_code)}</span></div></div></Card.Content></Card.Root>
			<Card.Root class="gap-0 bg-card py-0"><Card.Header class="border-b border-border px-4 py-3"><Card.Title class="text-base">Payment history</Card.Title><Card.Description class="mt-0.5 text-xs">Partial payments are supported and update the balance automatically.</Card.Description></Card.Header><Card.Content class="p-0">{#if data.payments.length === 0}<div class="px-4 py-8 text-sm text-muted-foreground sm:px-5">No payments recorded yet.</div>{:else}<div class="divide-y divide-border">{#each data.payments as payment (payment.id)}<div class="flex items-center gap-3 px-4 py-3 sm:px-5"><span class="flex size-8 items-center justify-center rounded-md bg-emerald-500/10 text-emerald-600 dark:text-emerald-400"><CheckCircle2 class="size-4" /></span><div class="min-w-0 flex-1"><p class="text-sm font-medium">{formatMoney(payment.amount, data.invoice.currency_code)}</p><p class="mt-1 text-xs text-muted-foreground">{formatDate(payment.payment_date, { month: 'short', day: 'numeric', year: 'numeric' })} · {payment.method.replace('_', ' ')}</p></div>{#if payment.reference}<span class="max-w-40 truncate text-xs text-muted-foreground">{payment.reference}</span>{/if}</div>{/each}</div>{/if}</Card.Content></Card.Root>
		</div>

		<div class="space-y-4">
			{#if outstanding > 0 && data.invoice.status !== 'void'}<Card.Root class="gap-0 bg-card py-0"><Card.Header class="border-b border-border px-4 py-3"><Card.Title class="text-base">Record payment</Card.Title><Card.Description class="mt-0.5 text-xs">Balance remaining: {formatMoney(outstanding, data.invoice.currency_code)}.</Card.Description></Card.Header><Card.Content class="p-4"><form method="POST" action="?/recordPayment" class="space-y-4"><div class="space-y-1.5"><Label for="payment-amount">Amount</Label><Input id="payment-amount" name="amount" type="number" min="0.01" max={outstanding} step="0.01" value={outstanding.toFixed(2)} required /></div><div class="space-y-1.5"><Label for="payment-date">Payment date</Label><Input id="payment-date" name="payment_date" type="date" value={new Date().toISOString().slice(0, 10)} required /></div><div class="space-y-1.5"><Label for="payment-method">Method</Label><select id="payment-method" name="method" class="h-9 w-full rounded-md border border-input bg-background px-3 py-1.5 text-sm shadow-xs outline-none focus:border-ring focus:ring-3 focus:ring-ring/20"><option value="bank_transfer">Bank transfer</option><option value="card">Card</option><option value="cash">Cash</option><option value="check">Check</option><option value="other">Other</option></select></div><div class="space-y-1.5"><Label for="payment-reference">Reference <span class="font-normal text-muted-foreground">optional</span></Label><Input id="payment-reference" name="reference" placeholder="Transfer reference" /></div><Button type="submit" class="w-full"><CreditCard class="size-3.5" /> Record payment</Button></form></Card.Content></Card.Root>{/if}
			<Card.Root class="gap-0 bg-card py-0"><Card.Header class="border-b border-border px-4 py-3"><Card.Title class="text-base">Invoice notes</Card.Title><Card.Description class="mt-0.5 text-xs">Details saved with the invoice.</Card.Description></Card.Header><Card.Content class="space-y-4 p-4">{#if data.invoice.notes}<div><p class="text-xs font-medium text-muted-foreground">Notes</p><p class="mt-1 whitespace-pre-wrap text-sm leading-6">{data.invoice.notes}</p></div>{/if}{#if data.invoice.payment_instructions}<div><p class="text-xs font-medium text-muted-foreground">Payment instructions</p><p class="mt-1 whitespace-pre-wrap text-sm leading-6">{data.invoice.payment_instructions}</p></div>{/if}{#if !data.invoice.notes && !data.invoice.payment_instructions}<p class="text-sm text-muted-foreground">No notes added.</p>{/if}</Card.Content></Card.Root>
		</div>
	</div>
</div>
